application_product_product:
    resource: "@ApplicationProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

application_category_category:
    resource: "@ApplicationProductBundle/Resources/config/routing/category.yml"
    prefix:   /category
