parameters:
    application.product_manager.class: Application\ProductBundle\Manager\ProductManager

services:
    application.product_manager:
            class:        "%application.product_manager.class%"
            arguments: [ "@doctrine.orm.default_entity_manager" ]

