Application\ProductBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: Application\ProductBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        description:
            type: string
            length: '255'
        enabled:
            type: boolean
    oneToMany:
        products:
          targetEntity: Product
          mappedBy: category
    lifecycleCallbacks: {  }
