Application\ProductBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Application\ProductBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        description:
            type: string
            length: '255'
        enabled:
            type: boolean
    manyToOne:
        category:
           targetEntity: Category
           inversedBy: products
           joinColumn:
              name: category_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
