<?php

namespace Application\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    /**
     * @param $id
     * @return array
     */
    public function getWithCategories($id)
    {
        $query = $this->createQueryBuilder('a');
        $query->join('a.category', 'c')
            ->where('c.id = :category_id')
            ->setParameter('category_id', $id);
        return $query->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function listProduct()
    {
        $query = $this->createQueryBuilder('a')
            ->andWhere('a.enabled =:enabled')
            ->setParameter('enabled', true);
        return $query->getQuery()->getResult();
    }


}
